version: '3.8'

services:

  db:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: notes_db
      DB_USER: root
      DB_PASS: root
    expose:
      - "8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
