server {
    listen 80;

    # FRONTEND
    location / {
        proxy_pass http://frontend:80;
        try_files $uri $uri/ /index.html;
    }

    # BACKEND API
    location /api/ {
        proxy_pass http://backend:8080;
    }
}
